import React, { useEffect } from "react";
import styled from "styled-components";
import Head from "next/head";
import Questions from "../../../components/Internship/Question";
import { useRouter } from "next/router";
import axios from "axios";

const question = () => {
  return (
    <>
      <Head>
        <title>Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Questions />
    </>
  );
};

export default question;
