import React from "react";
import Head from "next/head";
import Detail from "../components/Intership/Detail";

const detail = () => {
  return (
    <>
      <Head>
        <title>Intership</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Detail />
    </>
  );
};

export default detail;
