import React from "react";
import styled from "styled-components";
import Head from "next/head";
import Questions from "../components/Intership/Question";

const questions = () => {
  return (
    <>
      <Head>
        <title>Intership</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Questions />
    </>
  );
};

export default questions;

const Container = styled.div``;
