import React from "react";
import Head from "next/head";
import Contact from "../components/Contact";

const contact = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
    </>
  );
};

export default contact;
