import React from "react";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import Contactus from "./components/homepage/parts/Contactus";
import Head from "next/head";

const signup = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Contactus />
      <Footer />
    </>
  );
};

export default signup;
