import Head from "next/head";
import Categories from "./components/homepage/categories";
import Contactus from "./components/homepage/Contactus";
import Locations from "./components/homepage/locations";
import Section from "./components/homepage/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section />
      <Categories />
      <Locations />
      <Contactus />
    </>
  );
}
