import React from "react";
import Head from "next/head";
import styled from "styled-components";
import Link from "next/link";
const intershipdetail = () => {
  return (
    <>
      <Head>
        <title>Intership</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header>
        <div className="left">
          <img src="/intershipdetail/hiringbird-logo.png" alt="" />
        </div>
        <div className="hamburger">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className=""
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </div>
        <div className="menu">
          <a href="#">About Us</a>
          <a href="#">Contact Us</a>
          <button>Find Interships</button>
          <div className="icons"></div>
        </div>
      </Header>
      {/* search box */}
      <SearchContainer>
        <InputContainer>
          <InputField placeholder="e.g. UX Design or HB1234"></InputField>
          <Img src="/intershipdetail/line.svg" />
          <InputField placeholder="city, state or zip code"></InputField>
        </InputContainer>
        <Button>Search</Button>
      </SearchContainer>
      {/* body */}
      <Body>
        <div className="backbtn">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className=""
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M15 19l-7-7 7-7"
            />
          </svg>
          <a href="#">Back</a>
        </div>
        <div className="content">
          <div className="content_head">
            <div className="left">
              <h2>UI/UX Design Intern</h2>
              <div className="flex">
                <h4>Skilzen</h4>
                <div className="link">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="#F898A6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                  <a href="#">www.skilzen.com</a>
                </div>
              </div>
              <div className="flex">
                <p>2 Days ago</p>
                <p>15 Applicants applied</p>
              </div>
            </div>
            <div className="right">
              <img src="/intershipdetail/skillzen.png" alt="" />
            </div>
          </div>

          {/* desc */}
          <div className="content_desc">
            <div className="top">
              <div className="wrap">
                <h5>Stipend</h5>
                <h3>7500 - 10000 INR</h3>
              </div>
              <div className="wrap">
                <h5>Intership type</h5>
                <h3>Work from Home</h3>
              </div>
              <div className="wrap">
                <h5>Number of openings</h5>
                <h3>2</h3>
              </div>
              <div className="wrap">
                <h5>Internship start date</h5>
                <h3>2 June 2021</h3>
              </div>
              <div className="wrap">
                <h5>Duration</h5>
                <h3>2 Months</h3>
              </div>
              <div className="wrap">
                <h5>Apply By</h5>
                <h3>29/05/2021</h3>
              </div>
            </div>
            <div className="bottom">
              <Link href="/intership/questions">
                <button>Apply Now</button>
              </Link>

              <div className="share">
                <img src="/intershipdetail/whatsapp-icon.png" alt="" />
                <p>Share</p>
              </div>
            </div>
          </div>

          {/* detailed desc */}
          <div className="content_detailedDesc">
            <div className="common-container">
              <h1>Skills(s) Required</h1>
              <div className="childrens">
                <p>User Research</p>
                <p>User Research</p>
                <p>User Research</p>
                <p>User Research</p>
                <p>User Research</p>
              </div>
            </div>
            <div className="common-container">
              <h1>About Skilzen</h1>
              <p>
                Designers are responsible for the design of digitally-enabled
                products and services. They use their broad skillset across the
                service, interaction, and visual design domains to work on
                holistic design solutions, from early-stage idea generation
                until detailed design of service features and user stories in a
                digital product.
              </p>
            </div>
            <div className="common-container">
              <h1>Job Description</h1>
              <p>
                Designers are responsible for the design of digitally-enabled
                products and services. They use their broad skillset across the
                service, interaction, and visual design domains to work on
                holistic design solutions, from early-stage idea generation
                until detailed design of service features and user stories in a
                digital product.
              </p>
            </div>
            <div className="common-container">
              <h1>Selected intern's day-to-day responsibilities include:</h1>
              <p>
                1. Preparing and presenting designs, wireframes, and prototypes
                to internal teams and key stakeholders <br /> 2. Developing
                interaction flows, UI mockups, and low-fidelity prototypes{" "}
                <br /> 3. Since we are undergoing a website overhaul, you will
                contribute to designing our website pages <br /> 4. Developing
                an understanding of the end-users through secondary and primary
                researc <br /> 5. Conduct testing of applications, websites, and
                software to assess user experience <br /> 6. Identifying and
                troubleshooting UX problems <br /> 7. Creating infographics and
                other such collateral to present our clients.
              </p>
            </div>
            <div className="common-container">
              <h1>Who can Apply:</h1>
              <p>
                1. Have already graduated or are currently in any year of study{" "}
                <br />
                2. Have relevant skills and interests <br /> 3. Are available
                for a duration of at least 3 months <br /> 4. Are available for
                the work from home internship
              </p>
            </div>
            <div className="bottom">
              <button>Apply</button>
              <a href="#">Report Spam</a>
            </div>
          </div>
        </div>
      </Body>
      {/* footer */}
    </>
  );
};

export default intershipdetail;

const Header = styled.div`
  display: flex;
  align-items: center;
  width: min(98%, 90rem);
  margin-inline: auto;
  .left {
    flex: 1;
  }
  .hamburger {
    @media (min-width: 600px) {
      display: none;
    }
    svg {
      height: 2rem;
      cursor: pointer;
    }
  }
  .menu {
    display: flex;
    align-items: center;
    @media (max-width: 600px) {
      display: none;
    }
    a {
      margin-right: 2em;
      font-weight: 500;
      font-size: 16px;
      color: #404366;
      text-decoration: none;
    }
    button {
      margin-right: 1em;
      background-color: #f26a7e;
      padding: 10px 26px;
      color: #fff;
      border: none;
      font-weight: 600;
      font-size: 14px;
      border-radius: 4px;
    }
  }
`;

const SearchBox = styled.div`
  height: 10rem;
  background: #f5f5f5;
`;

const Body = styled.div`
  width: min(95%, 80rem);
  margin-inline: auto;
  margin-bottom: 1em;
  .backbtn {
    margin: 1rem 0;
    display: flex;
    align-items: center;
    svg {
      height: 1.5em;
      color: #98a8b8;
    }
    a {
      font-size: 20px;
      color: #98a8b8;
      text-decoration: none;
    }
  }
  .content {
    border: 1px solid #c9cbe2;
    border-radius: 15px;
    padding: 2rem;
    .content_head {
      border-bottom: 1px solid #c9cbe2;
      padding-bottom: 1.5em;
      display: flex;
      justify-content: space-between;
      .left {
        h2 {
          color: #404366;
          font-weight: 500;
          font-size: 28px;
          margin-bottom: 0.5em;
        }
        .flex {
          display: flex;
          align-items: center;
          margin-top: 0.5em;
          .link {
            margin-left: 0.6em;
            display: flex;
            align-items: center;
            svg {
              height: 1.2rem;
            }
          }
          h4 {
            font-weight: 500;
            font-size: 20px;
            color: #404366;
          }
          a {
            color: #f898a6;
            margin-left: 0.2em;
          }
          p + p {
            margin-left: 0.6em;
          }
          p {
            font-size: 18px;
            color: #a9accb;
          }
        }
      }
    }
    .content_desc {
      padding: 1.5em 0;
      border-bottom: 1px solid #c9cbe2;
      .top {
        display: flex;
        flex-flow: row wrap;
        max-width: 60rem;
        width: 100%;
        .wrap {
          flex-basis: 30%;
          /* flex-basis: 14rem; */
          /* flex-basis: 31.3%; */
          margin: 1.8% 0;
          @media (max-width: 818px) {
          }
          @media (max-width: 600px) {
            flex-basis: 50%;
          }
          h5 {
            font-weight: 500;
            font-size: 16px;
            color: #a9accb;
            margin-bottom: 0.6em;
            @media (max-width: 818px) {
              font-size: 13px;
            }
          }
          h3 {
            font-weight: 600;
            font-size: 19px;
            color: #404366;
            @media (max-width: 818px) {
              font-size: 16px;
            }
          }
        }
      }
      .bottom {
        margin-top: 1em;
        display: flex;
        align-items: center;
        button {
          font-weight: 500;
          font-size: 16px;
          color: #404366;
          padding: 13px 22px;
          border: 1px solid #f898a6;
          margin-right: 2em;
          background-color: #fff;
          border-radius: 4px;
          cursor: pointer;
        }
        .share {
          display: flex;
          cursor: pointer;
          p {
            margin-left: 0.4rem;
          }
        }
      }
    }
    .content_detailedDesc {
      padding-top: 1.5em;
      .bottom {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding-top: 1em;
        button {
          font-weight: 500;
          font-size: 16px;
          color: #404366;
          padding: 13px 22px;
          border: 1px solid #f898a6;
          margin-right: 2em;
          background-color: #fff;
          border-radius: 4px;
          cursor: pointer;
        }
        a {
          font-weight: 500;
          font-size: 15px;
          line-height: 22px;
          color: #404366;
        }
      }
      .common-container {
        margin-bottom: 1em;
        .childrens {
          display: flex;
          flex-flow: row wrap;
          padding: 1em 0;
          p {
            font-weight: 600;
            line-height: 24px;

            color: #404366;
          }
          * {
            margin: 0 1em;
            flex-basis: 8em;
          }
        }
        h1 {
          font-weight: 600;
          font-size: 26px;
          color: #404366;
          margin-bottom: 0.5em;
        }
        p {
          font-size: 17px;
          line-height: 29px;
          color: #5c5f85;
        }
        &:last-child {
          margin-bottom: 0;
        }
      }
    }
  }
`;

const SearchContainer = styled.div`
  display: flex;
  margin: 45px auto;
  width: min(95%, 50rem);
  @media (max-width: 600px) {
    display: none;
  }
`;

const Button = styled.button`
  background-color: #f26a7e;
  border-radius: 6px;
  padding: 17px 35px;
  border: none;
  color: #fff;
  font-weight: 500;
  font-size: 16px;
  cursor: pointer;
  margin-left: 0.6em;
`;

const InputField = styled.input`
  border: none;
  width: 100%;
  outline: none;
  padding: 0 20px;
  color: #404366;
  &::placeholder {
    font-size: 13px;
    font-weight: 500;
    color: #c9cbe2;
  }
`;

const InputContainer = styled.div`
  display: flex;
  width: 85%;
  margin: 0 auto;
  border: 1px solid #c9cbe2;
  border-radius: 2px;
`;

const Img = styled.img`
  height: 82%;
  display: flex;
  align-items: center;
  padding-top: 6px;
`;
